.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GPICVIEW 1 "Sep 10, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gpicview \- lightweight image viewer
.SH SYNOPSIS
.B gpicview
.RI [ options ] " file"
.SH DESCRIPTION
This manual page documents briefly the
.B gpicview
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgpicview\fP is a simple image viewer that features:
  * Extremely lightweight and fast with low memory usage
  * Very suitable for default image viewer of desktop system
  * Simple and intuitive interface
  * Minimal lib dependency: Only pure GTK+ is used
  * Desktop independent: Doesn't require any specific desktop environment
  * Open source, licensed under GNU GPL
.SH OPTIONS
Currently there are no options available.
.SH AUTHOR
gpicview was written by PCMan (Hong Jen Yee) <pcman.tw@gmail.com>.
.PP
This manual page was written by PCMan <pcman.tw@gmail.com>,
for the Debian project (but may be used by others).
