.TH GPICVIEW "1" "July 2024" "gpicview" "User Commands"
.SH NAME
gpicview \- lightweight image viewer
.SH SYNOPSIS
.B gpicview
[\fIOPTION\fR] [\fIfile\fR]
.SH DESCRIPTION
  * Extremely lightweight and fast with low memory usage
  * Very suitable for the default image viewer of desktop systems
  * Simple and intuitive interface
  * Minimal library dependencies
  * Desktop independent \(en no specific desktop environment required
.SH OPTIONS
.TP
\fB\-\-slideshow\fR
Start slideshow
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.TP
\fB\-?\fR, \fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ options
.TP
\fB\-\-help\-all\fR
Show all help options
.SH AUTHOR
GPicView was written by PCMan (Hong Jen Yee) <pcman.tw@gmail.com>.
.PP
This manual page was written by PCMan <pcman.tw@gmail.com> and revised by
Ingo Br\[:u]ckl.
